# Setup Inicial

## Importando Bibliotecas

In [51]:
import os
import warnings
import numpy as np
from google.cloud import bigquery
from scipy.stats import chi2_contingency, spearmanr, f_oneway

## Autenticando o Client do BigQuery

In [52]:
warnings.filterwarnings('ignore')
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = './bigquery_api_key.json'
client = bigquery.Client()

# Questão 1 — Extração e Análise Exploratória com SQL

## 1.1 — Extração de Dados (SQL)

### Qual é o volume de sessões, usuários únicos e transações por mês?

In [53]:
# Converte a string de data para uma data truncada por mês e ano. Ex: 22/06/2016 -> 01/06/2016
# Calcula as visitas, usuários e transações agrupadas por mês.
query_1 = """
SELECT
  DATE_TRUNC(PARSE_DATE('%Y%m%d', date), MONTH) as month_year,
  COUNT(DISTINCT visitId) AS unique_visits,
  COUNT(DISTINCT fullVisitorId) AS unique_users,
  SUM(totals.transactions) AS transactions
FROM
  `bigquery-public-data.google_analytics_sample.ga_sessions_*`
GROUP BY
  month_year
ORDER BY
  month_year
"""

unique_visits_df = client.query(query_1).to_dataframe()

display(unique_visits_df)

    month_year  unique_visits  unique_users  transactions
0   2016-08-01          73494         61699          1241
1   2016-09-01          69729         59121           904
2   2016-10-01          95409         84901           919
3   2016-11-01         111201         99734           955
4   2016-12-01          77589         63839          1450
5   2017-01-01          63585         53041           713
6   2017-02-01          61122         51364           733
7   2017-03-01          68574         57888           993
8   2017-04-01          65935         55681           959
9   2017-05-01          64217         52233          1160
10  2017-06-01          62483         52067           971
11  2017-07-01          70478         58569          1072
12  2017-08-01           2509          2293            45

Observa-se que o último mês de 2017 parece estar incompleto, devido ao número baixo em todas as variáveis.

### Quais canais de aquisição (source/medium) geram mais receita? E quais têm melhor taxa de conversão?

In [54]:
# Calcula a receita e a receita média por canal de aquisição. Após a CTE, calcula o share de revenue
# incluindo e excluindo o canal direto. Além disso, converte um número decimal em porcentagem da
# seguinte forma: 0,0234 -> 2,34%
query_2 = """
WITH revenue_per_channel AS (
  SELECT
    CONCAT(trafficSource.source, ' / ', trafficSource.medium) AS acquisition_channel,
    SUM(COALESCE(totals.totalTransactionRevenue, 0)) AS revenue,
    AVG(COALESCE(totals.totalTransactionRevenue, 0)) AS mean_revenue
  FROM
    `bigquery-public-data.google_analytics_sample.ga_sessions_*`
  GROUP BY
    acquisition_channel
  ORDER BY
    revenue DESC
)

SELECT
  *,
  CONCAT(FORMAT('%.2f', (revenue / SUM(revenue) OVER ()) * 100), '%') AS revenue_share,
  CASE 
    WHEN acquisition_channel = '(direct) / (none)' THEN NULL 
    ELSE CONCAT(
           FORMAT(
             '%.2f', 
             (revenue / SUM(
                CASE WHEN acquisition_channel = '(direct) / (none)' THEN 0 ELSE revenue END
             ) OVER()) * 100
           ),
           '%'
         ) 
  END AS revenue_share_excluding_direct
FROM
  revenue_per_channel
ORDER BY
  revenue DESC
"""

source_revenue = client.query(query_2).to_dataframe()

display(source_revenue.head(6))

,acquisition_channel,revenue,mean_revenue,revenue_share,revenue_share_excluding_direct
0,(direct) / (none),1332591980000,3.587376e+06,74.86%,None
1,google / organic,238974970000,1.049664e+06,13.42%,53.40%
2,dfa / cpm,128787150000,2.264987e+07,7.23%,28.78%
3,google / cpc,27876250000,2.131538e+06,1.57%,6.23%
4,mail.google.com / referral,24830780000,1.704240e+07,1.39%,5.55%
5,dealspotr.com / referral,5873640000,1.112432e+07,0.33%,1.31%

Acima, há o Top 6 canais que mais trazem receita para a empresa. Observa-se que o canal direto detém a grande maioria da receita. Excluindo-o para que se tenha uma noção melhor do share de receita entre os canais de marketing, observa-se que pesquisas no google orgânicas e "dfa/cpm" trazem quase 90% das demais receitas.

In [55]:
# Calcula o número de sessões e taxa de conversão por canal de aquisição. Além de fazer a mesma 
# conversão de procetagem citada acima.
query_3 = """
SELECT
  CONCAT(trafficSource.source, ' / ', trafficSource.medium) AS acquisition_channel,
  COUNT(*) AS total_sessions,
  CONCAT(
    FORMAT(
      '%.2f', 
      SUM(COALESCE(totals.transactions, 0)) / COUNT(*) * 100
    ),
    '%'
  ) AS conversion_rate
FROM
  `bigquery-public-data.google_analytics_sample.ga_sessions_*`
GROUP BY
  acquisition_channel
ORDER BY
  SUM(COALESCE(totals.transactions, 0)) / COUNT(*) DESC
LIMIT 5
"""

convertion_rate_df = client.query(query_3).to_dataframe()

display(convertion_rate_df)

                acquisition_channel  total_sessions conversion_rate
0           basecamp.com / referral               2          50.00%
1           mail.aol.com / referral               3          33.33%
2  us-mg5.mail.yahoo.com / referral               4          25.00%
3    calendar.google.com / referral               5          20.00%
4        chat.google.com / referral               7          14.29%

Observa-se, que o Top 5 de canais com a maior taxa de conversão é bem diferente dos canais com maior receita. Entretanto, isso se deve ao fato de terem um baixo número de sessões, logo, é mais fácil terem uma taxa de conversão maior. 

Ao se remover os canais com baixo número de sessões obtem-se a seguinte tabela:

In [56]:
# Repete o mesmo feito na query anterior, mas remove canais com menos de 100 sessões
query_4 = """
SELECT
  CONCAT(trafficSource.source, ' / ', trafficSource.medium) AS acquisition_channel,
  COUNT(*) AS total_sessions,
  CONCAT(
    FORMAT(
      '%.2f', 
      SUM(COALESCE(totals.transactions, 0)) / COUNT(*) * 100
    ),
    '%'
  ) AS conversion_rate
FROM
  `bigquery-public-data.google_analytics_sample.ga_sessions_*`
GROUP BY
  acquisition_channel
HAVING
  total_sessions > 100
ORDER BY
  SUM(COALESCE(totals.transactions, 0)) / COUNT(*) DESC
LIMIT 5
"""

convertion_rate_df_filtered = client.query(query_4).to_dataframe()

display(convertion_rate_df_filtered)

            acquisition_channel  total_sessions conversion_rate
0      dealspotr.com / referral             528           7.58%
1    mail.google.com / referral            1457           4.80%
2     l.facebook.com / referral             795           3.77%
3  groups.google.com / referral            1025           3.71%
4                  google / cpm             496           3.63%

Desta forma, conseguimos um dado mais confiável para qual é o canal com maior conversão. Neste caso, é o `dealspotr.com / referral` que também está presente nos top canais de receita, sendo o 6° colocado.

### Qual é a distribuição de sessões por dispositivo (desktop, mobile, tablet)?

In [57]:
# Calcula as sessões únicas por dispositivo, e converte a proporção em uma string de porcentagem.
query_5 = """
WITH sessions_per_device AS (
  SELECT
    device.deviceCategory AS device,
    COUNT(DISTINCT visitId) AS unique_sessions
  FROM
    `bigquery-public-data.google_analytics_sample.ga_sessions_*`
  GROUP BY
    device
)

SELECT
  *,
  CONCAT(FORMAT('%.2f', (unique_sessions / SUM(unique_sessions) OVER ()) * 100), '%') AS session_share
FROM
  sessions_per_device
ORDER BY
  unique_sessions DESC
"""

device_sessions_df = client.query(query_5).to_dataframe()

display(device_sessions_df)

    device  unique_sessions session_share
0  desktop           653795        73.32%
1   mobile           207512        23.27%
2   tablet            30395         3.41%

Nota-se que a maioria das sessões vêm de usuários de Desktop, enquanto um número bem baixo delas vêm dos usuários de tablet.

### Quais são os 10 produtos mais vendidos em receita e em volume de unidades?

In [58]:
# Calcula a revenue total por produto e depois da CTE calcula o share da revenue total
query_6 = """
WITH revenue_per_product AS (
  SELECT
    p.v2ProductName AS product_name,
    SUM(COALESCE(p.productRevenue, 0)) AS total_revenue
  FROM
    `bigquery-public-data.google_analytics_sample.ga_sessions_*`,
    UNNEST(hits) AS h,
    UNNEST(h.product) AS p
  WHERE
    h.eCommerceAction.action_type = '6' -- Somente transações completas
  GROUP BY
    product_name
)

SELECT
  *,
  CONCAT(FORMAT('%.2f', (total_revenue / SUM(total_revenue) OVER ()) * 100), '%') AS revenue_share
FROM
  revenue_per_product
ORDER BY
  total_revenue DESC
LIMIT
  10
"""

product_revenue_df = client.query(query_6).to_dataframe()

display(product_revenue_df)

,product_name,total_revenue,revenue_share
0,Google Men's Zip Hoodie,47636271605,2.73%
1,26 oz Double Wall Insulated Bottle,44454491527,2.55%
2,Google 22 oz Water Bottle,42995041996,2.47%
3,Leatherette Journal,38563457656,2.21%
4,Google Sunglasses,35490321293,2.04%
5,Google Metallic Notebook Set,28846596814,1.66%
6,Google Men's 100% Cotton Short Sleeve Hero Tee...,28047612114,1.61%
7,Recycled Paper Journal Set,27918170430,1.60%
8,Google Men's 100% Cotton Short Sleeve Hero Tee...,27856018891,1.60%
9,Google Hard Cover Journal,25432673189,1.46%

In [59]:
# Calcula a quantidade total por produto e depois da CTE calcula o share da quantidade total
query_7 = """
WITH quantity_per_product AS (
  SELECT
    p.v2ProductName AS product_name,
    SUM(COALESCE(p.productQuantity, 0)) AS product_quantity
  FROM
    `bigquery-public-data.google_analytics_sample.ga_sessions_*`,
    UNNEST(hits) AS h,
    UNNEST(h.product) AS p
  WHERE
    h.eCommerceAction.action_type = '6' -- Somente transações completas
  GROUP BY
    product_name
)

SELECT
  *,
  CONCAT(FORMAT('%.2f', (product_quantity / SUM(product_quantity) OVER ()) * 100), '%') AS product_quantity_share
FROM
  quantity_per_product
ORDER BY
  product_quantity DESC
LIMIT
  10
"""

product_quantity_df = client.query(query_7).to_dataframe()

display(product_quantity_df)

,product_name,product_quantity,product_quantity_share
0,Maze Pen,16618,7.04%
1,Google 22 oz Water Bottle,15206,6.44%
2,Google Sunglasses,10981,4.65%
3,Recycled Paper Journal Set,7800,3.30%
4,Ballpoint Pen Blue,6512,2.76%
5,Google Laptop and Cell Phone Stickers,5528,2.34%
6,Google Metallic Notebook Set,5447,2.31%
7,Recycled Mouse Pad,5349,2.27%
8,Sport Bag,4948,2.10%
9,Galaxy Screen Cleaning Cloth,4904,2.08%

Pode-se observar que os produtos com maior quantidade vendida não coincidem necessariamente com os produtos que geram mais receita, evidenciando que os itens mais caros não são, obrigatoriamente, os mais populares.

### Qual é a taxa de rejeição (bounce rate) por canal? Existe diferença significativa entre eles?

In [60]:
# Calcula o bounce rate por canals
query_8 = """
SELECT
  CONCAT(trafficSource.source, ' / ', trafficSource.medium) AS acquisition_channel, 
  COUNT(*) AS total_sessions,
  CONCAT(
    FORMAT(
      '%.2f',
      SUM(COALESCE(totals.bounces, 0)) / COUNT(*) * 100
    ),
    '%'
  ) AS bounce_rate
FROM
  `bigquery-public-data.google_analytics_sample.ga_sessions_*`
GROUP BY
  acquisition_channel
ORDER BY
  SUM(COALESCE(totals.bounces, 0)) / COUNT(*) DESC
"""

bounce_rate_df = client.query(query_8).to_dataframe()

display(bounce_rate_df)

                       acquisition_channel  total_sessions bounce_rate
0              en.wikipedia.org / referral               6     100.00%
1          news.ycombinator.com / referral               1     100.00%
2              images.google.lt / referral               2     100.00%
3    int.search.mywebsearch.com / referral               1     100.00%
4         search.incredibar.com / referral               3     100.00%
..                                     ...             ...         ...
277       tweetdeck.twitter.com / referral               1       0.00%
278              search.pch.com / referral               1       0.00%
279           computerworld.com / referral               1       0.00%
280           gsuite.google.com / referral               1       0.00%
281                   google.no / referral               1       0.00%

[282 rows x 3 columns]

Como pode-se observar na tabela acima, há uma grande diferença do bounce rate de acordo com o canal. Mas, novamente, temos canais com pouquíssimas sessões. Logo, os removeremos para termos um número mais concreto.

In [61]:
# Calcula o bounce rate por canal, excluindo canais com menos de 100 sessões.
query_9 = """
SELECT
  CONCAT(trafficSource.source, ' / ', trafficSource.medium) AS acquisition_channel, 
  COUNT(*) AS total_sessions,
  CONCAT(
    FORMAT(
      '%.2f',
      SUM(COALESCE(totals.bounces, 0)) / COUNT(*) * 100
    ),
    '%'
  ) AS bounce_rate
FROM
  `bigquery-public-data.google_analytics_sample.ga_sessions_*`
GROUP BY
  acquisition_channel
HAVING
  total_sessions > 100
ORDER BY
  SUM(COALESCE(totals.bounces, 0)) / COUNT(*) DESC
"""

bounce_rate_df_filtered = client.query(query_9).to_dataframe()

display(bounce_rate_df_filtered)

                       acquisition_channel  total_sessions bounce_rate
0         int.search.tb.ask.com / referral             110      79.09%
1                   m.baidu.com / referral             142      71.83%
2                          t.co / referral            1529      70.37%
3                          baidu / organic            3356      67.79%
4      productforums.google.com / referral             364      67.58%
5            support.google.com / referral             101      67.33%
6                   youtube.com / referral          212602      65.99%
7                l.facebook.com / referral             795      63.14%
8                m.facebook.com / referral            3365      61.04%
9                  google.co.jp / referral             356      60.67%
10                           ask / organic             270      60.37%
11                 google.co.uk / referral             194      56.19%
12  googleads.g.doubleclick.net / referral             143      55.24%
13                    Partners / affiliate           16403      53.05%
14         analytics.google.com / referral           16172      52.29%
15                 facebook.com / referral            2296      52.09%
16                dealspotr.com / referral             528      51.33%
17          optimize.google.com / referral             175      49.14%
18              plus.google.com / referral             524      49.05%
19                        google / organic          227668      48.94%
20             seroundtable.com / referral             126      48.41%
21                    qiita.com / referral            1813      48.04%
22              lunametrics.com / referral             148      47.97%
23                phandroid.com / referral             222      47.75%
24               duckduckgo.com / referral             207      45.89%
25                         yahoo / organic            1478      45.60%
26                 sashihara.jp / referral             277      44.77%
27                    quora.com / referral            1546      43.14%
28                   google.com / referral            4669      42.64%
29            groups.google.com / referral            1025      42.05%
30                       (direct) / (none)          371467      41.80%
31                          bing / organic            1529      41.79%
32              docs.google.com / referral             388      41.49%
33                   reddit.com / referral            2022      41.05%
34              mail.google.com / referral            1457      37.54%
35                            google / cpc           13078      37.01%
36                               dfa / cpm            5686      36.07%
37                            google / cpm             496      35.28%
38             sites.google.com / referral            2983      33.46%
39      siliconvalley.about.com / referral            2097      31.19%
40                  s0.2mdn.net / referral             181      30.39%
41              blog.golang.org / referral             742      24.80%

Agora, mesmo com os dados filtrados, ainda chegamos na mesma conclusão: O canal é sim um fator que influencia o bounce rate.

## 1.2 — Análise Estatística

### Há diferença estatisticamente significativa na taxa de conversão entre dispositivos?

Para avaliar se há diferença estatisticamente significativa na taxa de conversão entre os diferentes dispositivos, utilizaremos o teste de qui-quadrado de independência. Esse teste permite verificar se a conversão está associada ao tipo de dispositivo, comparando as proporções de conversão observadas com aquelas que seriam esperadas caso o dispositivo não influenciasse na conversão.

In [62]:
# Conta quantas converssões e quantas não converssões cada dispositivo teve
query_10= """
SELECT
  device.deviceCategory AS device,
  SUM(CASE WHEN totals.transactions > 0 THEN 1 ELSE 0 END) AS conversions,
  COUNT(*) - SUM(CASE WHEN totals.transactions > 0 THEN 1 ELSE 0 END) AS non_conversions
FROM
  `bigquery-public-data.google_analytics_sample.ga_sessions_*`
GROUP BY
  device
"""

convertion_df = client.query(query_10).to_dataframe()

contingency_table = convertion_df[['conversions', 'non_conversions']].T
contingency_table.columns = convertion_df['device']
contingency_table = contingency_table.astype(int)
display(contingency_table)

chi2, p, dof, expected = chi2_contingency(contingency_table)
print(f"Chi2: {chi2:.2f}, p-valor: {p:.4f}")

device           desktop  mobile  tablet
conversions        10528     856     168
non_conversions   653951  207869   30281

Chi2: 1867.32, p-valor: 0.0000

O p-valor do teste foi igual a um número muito próximo de zero. Portanto, há evidências de que a taxa de conversão é diferente entre os dispositivos, sendo desktop o dispositivo com maior taxa de conversão, enquanto mobile tem a menor taxa de conversão.

In [63]:
convertion_df['conversion_rate'] = (
    convertion_df['conversions'] / (convertion_df['conversions'] + convertion_df['non_conversions'])
) * 100

conversion_rate_table = convertion_df[['device', 'conversion_rate']].set_index('device')

conversion_rate_table['conversion_share'] = (conversion_rate_table['conversion_rate'] / conversion_rate_table['conversion_rate'].sum()) * 100
conversion_rate_table = conversion_rate_table.round(2)

conversion_rate_table['conversion_rate'] = conversion_rate_table['conversion_rate'].astype(str) + '%'
conversion_rate_table['conversion_share'] = conversion_rate_table['conversion_share'].astype(str) + '%'

display(conversion_rate_table.reset_index())

    device conversion_rate conversion_share
0  desktop           1.58%           62.22%
1   mobile           0.41%           16.11%
2   tablet           0.55%           21.67%

### A receita média por transação varia entre os principais canais de aquisição?

In [64]:
# Calcula a média de receita por canal e exclui canais com menos de 100 sessões. Após isso, filtra
# os top 15 canais com mais receita média. E então pega todas as sessões desse canais e sua receita.
query_11 = """
WITH channel_stats AS (
  SELECT
    CONCAT(trafficSource.source, ' / ', trafficSource.medium) AS acquisition_channel,
    COUNT(*) AS total_sessions,
    AVG(COALESCE(totals.transactionRevenue, 0)) AS mean_revenue
  FROM
    `bigquery-public-data.google_analytics_sample.ga_sessions_*`
  WHERE
    trafficSource.source IS NOT NULL
    AND trafficSource.medium IS NOT NULL
  GROUP BY
    acquisition_channel
  HAVING
    total_sessions >= 100
),

top_channels AS (
  SELECT
    acquisition_channel
  FROM
    channel_stats
  ORDER BY
    mean_revenue DESC
  LIMIT 15
)

SELECT
  c.acquisition_channel,
  COALESCE(t.totals.transactionRevenue, 0) AS transaction_revenue
FROM
  `bigquery-public-data.google_analytics_sample.ga_sessions_*` AS t
JOIN
  top_channels AS c
ON
  CONCAT(t.trafficSource.source, ' / ', t.trafficSource.medium) = c.acquisition_channel
"""

channels_rev_df = client.query(query_11).to_dataframe()

channel_counts = channels_rev_df['acquisition_channel'].value_counts()
top_channels = channel_counts[channel_counts > 100].index
channels_rev_df_top = channels_rev_df[channels_rev_df['acquisition_channel'].isin(top_channels)]

revenue_by_channel = [channels_rev_df_top[channels_rev_df_top['acquisition_channel'] == ch]['transaction_revenue'].values
                      for ch in top_channels]

anova_stat, anova_p = f_oneway(*revenue_by_channel)

print(f"ANOVA F-statistic: {anova_stat:.2f}, p-value: {anova_p:.4f}")

ANOVA F-statistic: 32.16, p-value: 0.0000

Os canais usados para a comparação acima foram aqueles com ao menos 100 sessões e que rankearam entre os 15 com a maior média de receita. A análise de ANOVA que há diferenças estatisticamente significativas na receita média por transação entre os canais. Na tabela abaixo, estão presentes os canais que usamos para a comparação e sua receita média.

In [65]:
mean_rev = channels_rev_df.groupby('acquisition_channel').agg({
    'transaction_revenue': 'mean'
}).reset_index()

mean_rev['transaction_revenue'] = round(mean_rev['transaction_revenue'], 1)
mean_rev.sort_values(by='transaction_revenue', ascending = False)

             acquisition_channel  transaction_revenue
10    mail.google.com / referral           16010919.7
3                      dfa / cpm           13529444.2
2       dealspotr.com / referral           10777727.3
0              (direct) / (none)            3203986.1
6                   google / cpm            2701149.2
5                   google / cpc            1925123.1
8   groups.google.com / referral            1591473.2
13   sites.google.com / referral            1471934.3
9      l.facebook.com / referral            1312855.3
11      phandroid.com / referral            1224054.1
14               yahoo / organic             930284.2
7               google / organic             889435.4
1                 bing / organic             645990.8
4        facebook.com / referral             495500.9
12   seroundtable.com / referral             444365.1

### Existe correlação entre número de páginas visitadas por sessão e probabilidade de conversão?

In [66]:
# Seleciona a chance de conversão e número de páginas visitadas de cada visita única.
query_12 = """
SELECT
  visitId,
  totals.sessionQualityDim,
  totals.pageviews
FROM
  `bigquery-public-data.google_analytics_sample.ga_sessions_*`
WHERE
  totals.sessionQualityDim IS NOT NULL
"""

session_quality_df = client.query(query_12).to_dataframe()
session_quality_df = session_quality_df.dropna(subset=['sessionQualityDim', 'pageviews'])

corr, p_value = spearmanr(session_quality_df['sessionQualityDim'], session_quality_df['pageviews'])

print("Correlação de Spearman:", corr, "p-value:", p_value)

Correlação de Spearman: 0.629700618265973 p-value: 0.0

Como ambas as variávels são discretas, a correlação de Spearman é a ideal para o caso. A partir do teste de correlação, há evidências de que existe uma correlação positiva e significativa entre as variáveis. Ou seja, a chance de conversão de uma compra aumenta de acordo com o número de páginas visitadas.

### Qual é o intervalo de confiança (95%) para a taxa de conversão geral do site?

In [67]:
# Determina se uma visita resultou em conversão ou não.
query_13 ="""
SELECT
  visitId,
  IF(COALESCE(totals.transactions, 0) > 0, 1, 0) AS converted
FROM
  `bigquery-public-data.google_analytics_sample.ga_sessions_*`
"""

convertion_binary_df = client.query(query_13).to_dataframe()

n = len(convertion_binary_df)
p = convertion_binary_df['converted'].mean()
# Erro padrão
se = np.sqrt(p * (1 - p) / n)

ci_lower = p - 1.96 * se
ci_upper = p + 1.96 * se

print(f"Taxa de conversão: {(p * 100):.3f}%")
print(f"Intervalo de confiança 95%: [{(ci_lower * 100):.3f}% - {(ci_upper * 100):.3f}%]")

Taxa de conversão: 1.278%
Intervalo de confiança 95%: [1.255% - 1.302%]

A taxa de conversão do site é baixa (1,278%), mas o intervalo de confiança estreito ([1,255% – 1,302%]) nos indica que a estimativa é precisa. Podemos dizer que, em média, temos uma compra a cada 78 sessões.

## 1.3 — Insights e Recomendações

### Principais Insights

- **Origem do Tráfego:** O canal "(direct) / (none)" é responsável por aproximadamente 74,86% da receita total. Entre os canais de marketing (excluindo o direto), o tráfego orgânico do Google lidera com 53,4% de share de receita, seguido por campanhas de CPM (dfa / cpm) com 28,78%. Isso indica que a presença orgânica e campanhas de display são os principais motores de receita monitorada.

- **Discrepância entre Produtos Mais Vendidos e Mais Rentáveis:** Os produtos com maior volume de vendas (ex: Maze Pen, Google 22 oz Water Bottle) não são os mesmos que geram maior receita. Enquanto itens de menor valor impulsionam a quantidade de transações, produtos como Google Men's Zip Hoodie e 26 oz Double Wall Insulated Bottle lideram em receita.

- **Dispositivo de Acesso:** O tráfego e as conversões são concentrados em usuários de desktop, que representam 73,32% das sessões e 62,22% das converssões . O que indica que a jornada de compra atual aparenta ser mais otimizada para usuários de desktop. Além disso, o teste qui-quadrado confirmou que o dispositivo está associado à conversão (p < 0,001).

### Recomendação para a Equipe de Mídia

Com base nos dados, a equipe de mídia deve priorizar estratégias que maximizem a receita em vez do volume de vendas. Embora produtos de menor valor, como Maze Pen e Google 22 oz Water Bottle, tenham alto volume, itens como Google Men's Zip Hoodie e 26 oz Double Wall Insulated Bottle geram significativamente mais receita, indicando que as campanhas devem ser ajustadas para promover produtos de maior ticket médio. Além disso, o tráfego orgânico e as campanhas de display (CPM) são os principais motores de receita, então esforços de SEO e otimização de anúncios devem ser reforçados, especialmente para destacar produtos mais rentáveis.

Outro ponto relevante é o desempenho por dispositivo: a maior parte das sessões e conversões ocorre em desktop, e o teste estatístico confirma que o dispositivo influencia a conversão. Isso sugere que a experiência de compra e os anúncios devam ser priorizados para usuários de desktop, ao mesmo tempo em que se identificam e ajustam possíveis barreiras no mobile para não perder oportunidades de conversão. Dessa forma, a estratégia de mídia pode aumentar a receita de forma mais eficiente, concentrando esforços nos canais, produtos e dispositivos que trazem maior retorno.

### Limitações do Dataset

- **Esparsidade de Dados por Canal:** Como observado, muitos canais de aquisição possuem um volume de sessões insignificante (abaixo de 10 por ano), o que gera taxas de conversão artificialmente altas (ex: 50%) e distorce a análise de eficiência.

- **Dados Temporais Incompletos:** O dataset cobre o período de agosto de 2016 a agosto de 2017, porém o último mês registrado (agosto/2017) possui apenas 2.509 sessões, comparado a uma média superior a 60.000 nos meses anteriores. Isso impede uma comparação direta de crescimento anual para o mês de agosto, por exemplo.